/// @description Tunable jam constants for Equivalent Exchange.

#macro STARTING_HP 42
#macro STARTING_COINS 48

#macro TOTAL_WAVES 48
#macro BOSS_WAVE_INTERVAL 12

#macro TOWER_PLACEMENT_HP_COST 3
#macro TOWER_PLACEMENT_COST_STEP_TOWERS 2
#macro TOWER_PLACEMENT_COST_MAX_BONUS 4
#macro TOWER_MAX_LEVEL 3
#macro TOWER_DIRECTION_SPRITE_COUNT 12
#macro TOWER_DIRECTION_SPRITE_ANGLE_OFFSET 0
#macro TOWER_BASE_PROXIMITY_ALPHA_RADIUS 120
#macro TOWER_BASE_PROXIMITY_ALPHA_BOOST_MAX 0.28

#macro PRE_WAVE_DELAY_SECONDS 2.5
#macro BOSS_BANNER_SECONDS 1.8
#macro INTRO_LOCK_SECONDS 10
#macro INTRO_HOLD_SKIP_SECONDS 1
#macro CONFIRM_TIMEOUT_SECONDS 3

#macro WAVE_BASE_COUNT 6
#macro WAVE_GROWTH 2
#macro WAVE_EARLY_PRESSURE_START 4
#macro WAVE_EARLY_PRESSURE_END 12
#macro WAVE_EARLY_PRESSURE_BONUS 1

#macro ENEMY_BASIC_BASE_HP 24
#macro ENEMY_BASIC_BASE_SPEED 1.0
#macro ENEMY_SNAIL_SPEED_MULTIPLIER 0.65
#macro ENEMY_MANTIS_SPEED_MULTIPLIER 1.0
#macro ENEMY_SPIDER_SPEED_MULTIPLIER 1.45
#macro ENEMY_SNAIL_HP_MULTIPLIER 1.4
#macro ENEMY_MANTIS_HP_MULTIPLIER 1.0
#macro ENEMY_SPIDER_HP_MULTIPLIER 0.7
#macro ENEMY_BASIC_BASE_REWARD 3
#macro ENEMY_BASIC_REWARD_SCALE_PER_WAVE 0.03
#macro ENEMY_BASIC_LEAK_DAMAGE 1

#macro ENEMY_BOSS_BASE_HP 60
#macro ENEMY_BOSS_BASE_SPEED 0.75
#macro ENEMY_BOSS_BASE_REWARD 16
#macro ENEMY_BOSS_REWARD_SCALE_PER_WAVE 0.06
#macro ENEMY_BOSS_LEAK_DAMAGE 5
#macro BOSS_KILL_HP_REWARD 2

#macro ENEMY_HP_SCALE_PER_WAVE 0.16
#macro ENEMY_SPEED_SCALE_PER_WAVE 0.04
#macro ENEMY_DEATH_VFX_STEPS 10
#macro ENEMY_HIT_FLASH_SECONDS 0.08
#macro ENEMY_HIT_FLASH_STRENGTH 0.75
#macro ENEMY_HIT_AUDIO_GAIN_SCALE 0.58
#macro ENEMY_HIT_AUDIO_COOLDOWN_SECONDS 0.14
#macro ENEMY_HIT_AUDIO_PITCH_MIN 1.08
#macro ENEMY_HIT_AUDIO_PITCH_MAX 1.22
#macro LEAK_EDGE_FLASH_SECONDS 0.22
#macro LEAK_EDGE_FLASH_MAX_ALPHA 0.34
#macro LEAK_EDGE_FLASH_EDGE_PX 22

#macro COIN_DROP_LIFETIME_STEPS 600
#macro COIN_DROP_DEPTH -100000
#macro COIN_DROP_GRAVITY 0.35
#macro COIN_DROP_BOUNCE_MIN 3.4
#macro COIN_DROP_BOUNCE_MAX 5.2
#macro COIN_DROP_HORIZONTAL_SPEED 1.6
#macro COIN_DROP_BOUNCE_DAMPING 0.45
#macro COIN_DROP_GROUND_FRICTION 0.88
#macro COIN_DROP_MIN_BOUNCE_TO_SETTLE 0.5
#macro COIN_DROP_EXPIRE_FLASH_STEPS 60
#macro COIN_DROP_PULSE_AMOUNT 0.12

#macro COIN_SPEND_UI_PARTICLE_SCALE 0.75
#macro COIN_SPEND_UI_PARTICLE_SPEED_MIN 2.2
#macro COIN_SPEND_UI_PARTICLE_SPEED_MAX 5.4
#macro COIN_SPEND_UI_PARTICLE_GRAVITY 0.18
#macro COIN_SPEND_UI_PARTICLE_DRAG 0.965
#macro COIN_SPEND_UI_PARTICLE_LIFE_MIN 22
#macro COIN_SPEND_UI_PARTICLE_LIFE_MAX 34
#macro COIN_SPEND_UI_PARTICLE_SPIN_MAX 18

#macro VALUE_FX_ANCHOR_WORLD 0
#macro VALUE_FX_ANCHOR_GUI 1

#macro VALUE_FX_CATEGORY_COIN_GAIN 0
#macro VALUE_FX_CATEGORY_COIN_SPEND 1
#macro VALUE_FX_CATEGORY_HP_GAIN 2
#macro VALUE_FX_CATEGORY_HP_LOSS 3
#macro VALUE_FX_CATEGORY_DAMAGE 4

#macro VALUE_FX_MAX_ACTIVE 220
#macro VALUE_FX_BASE_WORLD_Y_OFFSET 30

#macro VALUE_FX_COIN_GAIN_LIFE_STEPS 52
#macro VALUE_FX_COIN_GAIN_RISE_DISTANCE 62
#macro VALUE_FX_COIN_GAIN_SCALE_START 1.7
#macro VALUE_FX_COIN_GAIN_SCALE_GROWTH 0.2

#macro VALUE_FX_COIN_SPEND_LIFE_STEPS 40
#macro VALUE_FX_COIN_SPEND_RISE_DISTANCE 50
#macro VALUE_FX_COIN_SPEND_SCALE_START 1.35
#macro VALUE_FX_COIN_SPEND_SCALE_GROWTH 0.14

#macro VALUE_FX_HP_GAIN_LIFE_STEPS 46
#macro VALUE_FX_HP_GAIN_RISE_DISTANCE 58
#macro VALUE_FX_HP_GAIN_SCALE_START 1.48
#macro VALUE_FX_HP_GAIN_SCALE_GROWTH 0.18

#macro VALUE_FX_HP_LOSS_LIFE_STEPS 46
#macro VALUE_FX_HP_LOSS_RISE_DISTANCE 58
#macro VALUE_FX_HP_LOSS_SCALE_START 1.48
#macro VALUE_FX_HP_LOSS_SCALE_GROWTH 0.18

#macro VALUE_FX_DAMAGE_LIFE_STEPS 34
#macro VALUE_FX_DAMAGE_RISE_DISTANCE 42
#macro VALUE_FX_DAMAGE_SCALE_START 1.18
#macro VALUE_FX_DAMAGE_SCALE_GROWTH 0.12

#macro VALUE_FX_DAMAGE_COLOUR_ARROW make_color_rgb(255, 236, 110)
#macro VALUE_FX_DAMAGE_COLOUR_SLOW make_color_rgb(122, 255, 186)
#macro VALUE_FX_DAMAGE_COLOUR_CANNON make_color_rgb(255, 168, 74)
#macro VALUE_FX_DAMAGE_COLOUR_FLAMER make_color_rgb(255, 98, 68)
#macro VALUE_FX_DAMAGE_COLOUR_FREEZE make_color_rgb(132, 206, 255)

#macro SPAWN_INTERVAL_START 0.72
#macro SPAWN_INTERVAL_END 0.45

#macro ARROW_L1_DAMAGE 8
#macro ARROW_L2_DAMAGE 13
#macro ARROW_L3_DAMAGE 20
#macro ARROW_L1_RANGE 165
#macro ARROW_L2_RANGE 180
#macro ARROW_L3_RANGE 200
#macro ARROW_L1_COOLDOWN 0.75
#macro ARROW_L2_COOLDOWN 0.65
#macro ARROW_L3_COOLDOWN 0.55

#macro SLOW_L1_DAMAGE 0
#macro SLOW_L2_DAMAGE 0
#macro SLOW_L3_DAMAGE 0
#macro SLOW_L1_RANGE 150
#macro SLOW_L2_RANGE 165
#macro SLOW_L3_RANGE 180
#macro SLOW_L1_COOLDOWN 1.1
#macro SLOW_L2_COOLDOWN 1.0
#macro SLOW_L3_COOLDOWN 0.85
#macro SLOW_L1_FACTOR 0.70
#macro SLOW_L2_FACTOR 0.60
#macro SLOW_L3_FACTOR 0.50
#macro SLOW_L1_DURATION 1.2
#macro SLOW_L2_DURATION 1.4
#macro SLOW_L3_DURATION 1.6
#macro SLOW_L1_SPLASH_RADIUS 80
#macro SLOW_L2_SPLASH_RADIUS 95
#macro SLOW_L3_SPLASH_RADIUS 110

#macro CANNON_L1_DAMAGE 12
#macro CANNON_L2_DAMAGE 18
#macro CANNON_L3_DAMAGE 27
#macro CANNON_L1_RANGE 190
#macro CANNON_L2_RANGE 210
#macro CANNON_L3_RANGE 230
#macro CANNON_L1_COOLDOWN 1.35
#macro CANNON_L2_COOLDOWN 1.2
#macro CANNON_L3_COOLDOWN 1.05
#macro CANNON_L1_SPLASH 55
#macro CANNON_L2_SPLASH 70
#macro CANNON_L3_SPLASH 88

#macro FLAMER_L1_DAMAGE 3
#macro FLAMER_L2_DAMAGE 5
#macro FLAMER_L3_DAMAGE 7
#macro FLAMER_L1_RANGE 130
#macro FLAMER_L2_RANGE 145
#macro FLAMER_L3_RANGE 160
#macro FLAMER_L1_COOLDOWN 0.28
#macro FLAMER_L2_COOLDOWN 0.24
#macro FLAMER_L3_COOLDOWN 0.2
#macro FLAMER_L1_CONE_ANGLE 70
#macro FLAMER_L2_CONE_ANGLE 80
#macro FLAMER_L3_CONE_ANGLE 90
#macro FLAMER_L1_BURN_DAMAGE 1
#macro FLAMER_L2_BURN_DAMAGE 1.5
#macro FLAMER_L3_BURN_DAMAGE 2.2
#macro FLAMER_L1_BURN_DURATION 1.1
#macro FLAMER_L2_BURN_DURATION 1.4
#macro FLAMER_L3_BURN_DURATION 1.8

#macro FREEZE_L1_DAMAGE 3
#macro FREEZE_L2_DAMAGE 5
#macro FREEZE_L3_DAMAGE 8
#macro FREEZE_L1_RANGE 145
#macro FREEZE_L2_RANGE 165
#macro FREEZE_L3_RANGE 185
#macro FREEZE_L1_COOLDOWN 1.25
#macro FREEZE_L2_COOLDOWN 1.1
#macro FREEZE_L3_COOLDOWN 0.95
#macro FREEZE_L1_DURATION 0.8
#macro FREEZE_L2_DURATION 1.0
#macro FREEZE_L3_DURATION 1.2

#macro ENEMY_BURN_TICK_SECONDS 0.25

#macro UPGRADE_TO_L2_ARROW 36
#macro UPGRADE_TO_L3_ARROW 60
#macro UPGRADE_TO_L2_SLOW 42
#macro UPGRADE_TO_L3_SLOW 66
#macro UPGRADE_TO_L2_CANNON 50
#macro UPGRADE_TO_L3_CANNON 78
#macro UPGRADE_TO_L2_FLAMER 52
#macro UPGRADE_TO_L3_FLAMER 84
#macro UPGRADE_TO_L2_FREEZE 56
#macro UPGRADE_TO_L3_FREEZE 90

// Validation target bands for manual scenario checks (waves 6 and 12).
#macro TARGET_W6_GREEDY_HP_MIN 4
#macro TARGET_W6_GREEDY_HP_MAX 14
#macro TARGET_W6_GREEDY_COINS_MIN 8
#macro TARGET_W6_GREEDY_COINS_MAX 26
#macro TARGET_W6_BALANCED_HP_MIN 16
#macro TARGET_W6_BALANCED_HP_MAX 30
#macro TARGET_W6_BALANCED_COINS_MIN 18
#macro TARGET_W6_BALANCED_COINS_MAX 42
#macro TARGET_W6_CONSERVATIVE_HP_MIN 26
#macro TARGET_W6_CONSERVATIVE_HP_MAX 38
#macro TARGET_W6_CONSERVATIVE_COINS_MIN 24
#macro TARGET_W6_CONSERVATIVE_COINS_MAX 54

#macro TARGET_W12_GREEDY_HP_MIN 0
#macro TARGET_W12_GREEDY_HP_MAX 12
#macro TARGET_W12_GREEDY_COINS_MIN 18
#macro TARGET_W12_GREEDY_COINS_MAX 48
#macro TARGET_W12_BALANCED_HP_MIN 14
#macro TARGET_W12_BALANCED_HP_MAX 30
#macro TARGET_W12_BALANCED_COINS_MIN 38
#macro TARGET_W12_BALANCED_COINS_MAX 86
#macro TARGET_W12_CONSERVATIVE_HP_MIN 18
#macro TARGET_W12_CONSERVATIVE_HP_MAX 36
#macro TARGET_W12_CONSERVATIVE_COINS_MIN 52
#macro TARGET_W12_CONSERVATIVE_COINS_MAX 110

#macro PATH_START_X -80
#macro PATH_START_Y 384
#macro ENEMY_SPAWN_OFFSET_X 12
#macro ENEMY_SPAWN_OFFSET_Y 12

#macro GAME_STATE_RUNNING 0
#macro GAME_STATE_GAME_OVER 1
#macro GAME_STATE_VICTORY 2
#macro GAME_STATE_INTRO 3

#macro AUDIO_GAIN_COMBAT 0.15
#macro AUDIO_GAIN_UI 0.39
#macro AUDIO_GAIN_AMBIENCE 0.18
#macro AUDIO_GAIN_ENEMY_CALL 0.26
#macro AUDIO_GAIN_LIFE_LOST 0.52
#macro AUDIO_MASTER_GAIN 0.25
#macro AUDIO_FLAMER_MIN_INTERVAL_SECONDS 0.12
#macro AUDIO_ENEMY_CALL_COOLDOWN_SECONDS 0.45
#macro AUDIO_ENEMY_CALL_MIN_SECONDS 5
#macro AUDIO_ENEMY_CALL_MAX_SECONDS 10
#macro AUDIO_BIRDSONG_MIN_SECONDS 7
#macro AUDIO_BIRDSONG_MAX_SECONDS 14

#macro PANEL_BLUR_ENABLED 1
#macro PANEL_BLUR_MAX_AREA_RATIO 0.42
#macro PANEL_BLUR_SAMPLE_OFFSET 3
#macro PANEL_BLUR_ALPHA 0.34
#macro PANEL_BLUR_DOWNSAMPLE 4
#macro PANEL_BLUR_PASSES 4
#macro PANEL_BLUR_PASS_STEP 1.25
#macro PANEL_BLUR_TINT_STRENGTH 0.18
#macro PANEL_BG_ALPHA_MULTIPLIER 0.78
#macro PANEL_TOP_HIGHLIGHT_ALPHA 0.20
#macro PANEL_SELECTED_ROW_BG_ALPHA 0.62
#macro PANEL_SELECTED_ROW_BORDER_ALPHA 0.55
#macro PANEL_SELECTED_ROW_INNER_SHADOW_ALPHA 0.26

#macro DECAL_TYPE_BLOOD 0
#macro DECAL_TYPE_ICE 1
#macro DECAL_TYPE_QUAKE 2
#macro DECAL_TYPE_FLAME 3
#macro DECAL_TYPE_SLOW 4
#macro DECAL_TYPE_TRACK 5

#macro DECAL_STATIC_MAX_MARKS 1400
#macro DECAL_DYNAMIC_MAX_MARKS 320

#macro DECAL_BLOOD_ALPHA_MIN 0.36
#macro DECAL_BLOOD_ALPHA_MAX 0.62
#macro DECAL_BLOOD_SIZE_MIN 6
#macro DECAL_BLOOD_SIZE_MAX 15

#macro DECAL_ICE_ALPHA 0.50
#macro DECAL_ICE_SIZE_MIN 11
#macro DECAL_ICE_SIZE_MAX 20

#macro DECAL_QUAKE_ALPHA 0.56
#macro DECAL_QUAKE_SIZE_MIN 14
#macro DECAL_QUAKE_SIZE_MAX 25

#macro DECAL_FLAME_ALPHA 0.48
#macro DECAL_FLAME_SIZE_MIN 10
#macro DECAL_FLAME_SIZE_MAX 18

#macro DECAL_SLOW_ALPHA 0.45
#macro DECAL_SLOW_SIZE_MIN 10
#macro DECAL_SLOW_SIZE_MAX 18

#macro DECAL_STATUS_GROUND_COOLDOWN_SECONDS 0.20
#macro DECAL_TRACK_LIFETIME_SECONDS 7.2
#macro DECAL_TRACK_ALPHA_MIN 0.68
#macro DECAL_TRACK_ALPHA_MAX 0.94
#macro DECAL_TRACK_SIZE_MIN 2.8
#macro DECAL_TRACK_SIZE_MAX 4.1
#macro DECAL_TRACK_PAIR_OFFSET 3.7
#macro DECAL_TRACK_STAMP_SPACING 5.3