/// @description Tunable jam constants for Equivalent Exchange.

#macro STARTING_HP 48
#macro STARTING_COINS 48

#macro TOTAL_WAVES 48
#macro BOSS_WAVE_INTERVAL 12

#macro TOWER_PLACEMENT_HP_COST 3
#macro TOWER_MAX_LEVEL 3
#macro TOWER_DIRECTION_SPRITE_COUNT 12
#macro TOWER_DIRECTION_SPRITE_ANGLE_OFFSET 0

#macro PRE_WAVE_DELAY_SECONDS 2.5
#macro BOSS_BANNER_SECONDS 1.8
#macro INTRO_LOCK_SECONDS 5
#macro CONFIRM_TIMEOUT_SECONDS 3

#macro WAVE_BASE_COUNT 6
#macro WAVE_GROWTH 2

#macro ENEMY_BASIC_BASE_HP 24
#macro ENEMY_BASIC_BASE_SPEED 1.0
#macro ENEMY_SNAIL_SPEED_MULTIPLIER 0.65
#macro ENEMY_MANTIS_SPEED_MULTIPLIER 1.0
#macro ENEMY_SPIDER_SPEED_MULTIPLIER 1.45
#macro ENEMY_SNAIL_HP_MULTIPLIER 1.4
#macro ENEMY_MANTIS_HP_MULTIPLIER 1.0
#macro ENEMY_SPIDER_HP_MULTIPLIER 0.7
#macro ENEMY_BASIC_BASE_REWARD 4
#macro ENEMY_BASIC_LEAK_DAMAGE 1

#macro ENEMY_BOSS_BASE_HP 60
#macro ENEMY_BOSS_BASE_SPEED 0.75
#macro ENEMY_BOSS_BASE_REWARD 20
#macro ENEMY_BOSS_LEAK_DAMAGE 5
#macro BOSS_KILL_HP_REWARD 3

#macro ENEMY_HP_SCALE_PER_WAVE 0.16
#macro ENEMY_SPEED_SCALE_PER_WAVE 0.04
#macro ENEMY_DEATH_VFX_STEPS 10
#macro ENEMY_HIT_FLASH_SECONDS 0.08
#macro ENEMY_HIT_FLASH_STRENGTH 0.75
#macro ENEMY_HIT_AUDIO_GAIN_SCALE 0.58
#macro ENEMY_HIT_AUDIO_COOLDOWN_SECONDS 0.14
#macro ENEMY_HIT_AUDIO_PITCH_MIN 1.08
#macro ENEMY_HIT_AUDIO_PITCH_MAX 1.22

#macro COIN_DROP_LIFETIME_STEPS 600
#macro COIN_DROP_DEPTH -100000
#macro COIN_DROP_GRAVITY 0.35
#macro COIN_DROP_BOUNCE_MIN 3.4
#macro COIN_DROP_BOUNCE_MAX 5.2
#macro COIN_DROP_HORIZONTAL_SPEED 1.6
#macro COIN_DROP_BOUNCE_DAMPING 0.45
#macro COIN_DROP_GROUND_FRICTION 0.88
#macro COIN_DROP_MIN_BOUNCE_TO_SETTLE 0.5
#macro COIN_DROP_EXPIRE_FLASH_STEPS 60
#macro COIN_DROP_PULSE_AMOUNT 0.12

#macro COIN_SPEND_UI_PARTICLE_SCALE 0.75
#macro COIN_SPEND_UI_PARTICLE_SPEED_MIN 2.2
#macro COIN_SPEND_UI_PARTICLE_SPEED_MAX 5.4
#macro COIN_SPEND_UI_PARTICLE_GRAVITY 0.18
#macro COIN_SPEND_UI_PARTICLE_DRAG 0.965
#macro COIN_SPEND_UI_PARTICLE_LIFE_MIN 22
#macro COIN_SPEND_UI_PARTICLE_LIFE_MAX 34
#macro COIN_SPEND_UI_PARTICLE_SPIN_MAX 18

#macro VALUE_FX_ANCHOR_WORLD 0
#macro VALUE_FX_ANCHOR_GUI 1

#macro VALUE_FX_CATEGORY_COIN_GAIN 0
#macro VALUE_FX_CATEGORY_COIN_SPEND 1
#macro VALUE_FX_CATEGORY_HP_GAIN 2
#macro VALUE_FX_CATEGORY_HP_LOSS 3
#macro VALUE_FX_CATEGORY_DAMAGE 4

#macro VALUE_FX_MAX_ACTIVE 220
#macro VALUE_FX_BASE_WORLD_Y_OFFSET 30

#macro VALUE_FX_COIN_GAIN_LIFE_STEPS 52
#macro VALUE_FX_COIN_GAIN_RISE_DISTANCE 62
#macro VALUE_FX_COIN_GAIN_SCALE_START 1.7
#macro VALUE_FX_COIN_GAIN_SCALE_GROWTH 0.2

#macro VALUE_FX_COIN_SPEND_LIFE_STEPS 40
#macro VALUE_FX_COIN_SPEND_RISE_DISTANCE 50
#macro VALUE_FX_COIN_SPEND_SCALE_START 1.35
#macro VALUE_FX_COIN_SPEND_SCALE_GROWTH 0.14

#macro VALUE_FX_HP_GAIN_LIFE_STEPS 46
#macro VALUE_FX_HP_GAIN_RISE_DISTANCE 58
#macro VALUE_FX_HP_GAIN_SCALE_START 1.48
#macro VALUE_FX_HP_GAIN_SCALE_GROWTH 0.18

#macro VALUE_FX_HP_LOSS_LIFE_STEPS 46
#macro VALUE_FX_HP_LOSS_RISE_DISTANCE 58
#macro VALUE_FX_HP_LOSS_SCALE_START 1.48
#macro VALUE_FX_HP_LOSS_SCALE_GROWTH 0.18

#macro VALUE_FX_DAMAGE_LIFE_STEPS 34
#macro VALUE_FX_DAMAGE_RISE_DISTANCE 42
#macro VALUE_FX_DAMAGE_SCALE_START 1.18
#macro VALUE_FX_DAMAGE_SCALE_GROWTH 0.12

#macro SPAWN_INTERVAL_START 0.75
#macro SPAWN_INTERVAL_END 0.45

#macro ARROW_L1_DAMAGE 8
#macro ARROW_L2_DAMAGE 13
#macro ARROW_L3_DAMAGE 20
#macro ARROW_L1_RANGE 165
#macro ARROW_L2_RANGE 180
#macro ARROW_L3_RANGE 200
#macro ARROW_L1_COOLDOWN 0.75
#macro ARROW_L2_COOLDOWN 0.65
#macro ARROW_L3_COOLDOWN 0.55

#macro SLOW_L1_DAMAGE 4
#macro SLOW_L2_DAMAGE 7
#macro SLOW_L3_DAMAGE 10
#macro SLOW_L1_RANGE 150
#macro SLOW_L2_RANGE 165
#macro SLOW_L3_RANGE 180
#macro SLOW_L1_COOLDOWN 1.1
#macro SLOW_L2_COOLDOWN 1.0
#macro SLOW_L3_COOLDOWN 0.85
#macro SLOW_L1_FACTOR 0.70
#macro SLOW_L2_FACTOR 0.60
#macro SLOW_L3_FACTOR 0.50
#macro SLOW_L1_DURATION 1.2
#macro SLOW_L2_DURATION 1.4
#macro SLOW_L3_DURATION 1.6

#macro CANNON_L1_DAMAGE 12
#macro CANNON_L2_DAMAGE 18
#macro CANNON_L3_DAMAGE 27
#macro CANNON_L1_RANGE 190
#macro CANNON_L2_RANGE 210
#macro CANNON_L3_RANGE 230
#macro CANNON_L1_COOLDOWN 1.35
#macro CANNON_L2_COOLDOWN 1.2
#macro CANNON_L3_COOLDOWN 1.05
#macro CANNON_L1_SPLASH 55
#macro CANNON_L2_SPLASH 70
#macro CANNON_L3_SPLASH 88

#macro FLAMER_L1_DAMAGE 3
#macro FLAMER_L2_DAMAGE 5
#macro FLAMER_L3_DAMAGE 7
#macro FLAMER_L1_RANGE 130
#macro FLAMER_L2_RANGE 145
#macro FLAMER_L3_RANGE 160
#macro FLAMER_L1_COOLDOWN 0.28
#macro FLAMER_L2_COOLDOWN 0.24
#macro FLAMER_L3_COOLDOWN 0.2
#macro FLAMER_L1_CONE_ANGLE 70
#macro FLAMER_L2_CONE_ANGLE 80
#macro FLAMER_L3_CONE_ANGLE 90
#macro FLAMER_L1_BURN_DAMAGE 1
#macro FLAMER_L2_BURN_DAMAGE 1.5
#macro FLAMER_L3_BURN_DAMAGE 2.2
#macro FLAMER_L1_BURN_DURATION 1.1
#macro FLAMER_L2_BURN_DURATION 1.4
#macro FLAMER_L3_BURN_DURATION 1.8

#macro FREEZE_L1_DAMAGE 3
#macro FREEZE_L2_DAMAGE 5
#macro FREEZE_L3_DAMAGE 8
#macro FREEZE_L1_RANGE 145
#macro FREEZE_L2_RANGE 165
#macro FREEZE_L3_RANGE 185
#macro FREEZE_L1_COOLDOWN 1.25
#macro FREEZE_L2_COOLDOWN 1.1
#macro FREEZE_L3_COOLDOWN 0.95
#macro FREEZE_L1_DURATION 0.8
#macro FREEZE_L2_DURATION 1.0
#macro FREEZE_L3_DURATION 1.2

#macro ENEMY_BURN_TICK_SECONDS 0.25

#macro UPGRADE_TO_L2_ARROW 28
#macro UPGRADE_TO_L3_ARROW 54
#macro UPGRADE_TO_L2_SLOW 34
#macro UPGRADE_TO_L3_SLOW 59
#macro UPGRADE_TO_L2_CANNON 40
#macro UPGRADE_TO_L3_CANNON 70
#macro UPGRADE_TO_L2_FLAMER 42
#macro UPGRADE_TO_L3_FLAMER 76
#macro UPGRADE_TO_L2_FREEZE 45
#macro UPGRADE_TO_L3_FREEZE 82

#macro PATH_START_X -80
#macro PATH_START_Y 384
#macro ENEMY_SPAWN_OFFSET_X 12
#macro ENEMY_SPAWN_OFFSET_Y 12

#macro GAME_STATE_RUNNING 0
#macro GAME_STATE_GAME_OVER 1
#macro GAME_STATE_VICTORY 2
#macro GAME_STATE_INTRO 3

#macro AUDIO_GAIN_COMBAT 0.15
#macro AUDIO_GAIN_UI 0.39
#macro AUDIO_GAIN_AMBIENCE 0.18
#macro AUDIO_GAIN_ENEMY_CALL 0.26
#macro AUDIO_GAIN_LIFE_LOST 0.52
#macro AUDIO_MASTER_GAIN 0.25
#macro AUDIO_FLAMER_MIN_INTERVAL_SECONDS 0.12
#macro AUDIO_ENEMY_CALL_COOLDOWN_SECONDS 0.45
#macro AUDIO_ENEMY_CALL_MIN_SECONDS 5
#macro AUDIO_ENEMY_CALL_MAX_SECONDS 10
#macro AUDIO_BIRDSONG_MIN_SECONDS 7
#macro AUDIO_BIRDSONG_MAX_SECONDS 14